# Generated by Django 5.2.3 on 2025-06-18 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='post',
            new_name='post_id',
        ),
    ]
